### ISSUE TITLE
NoMethodError: undefined method `root' for #<Gem::Source::Installed:0x007ff9c4ff0d50 @uri=nil>

### ISSUE THREAD

**Issue by gpakosz** [deivid-rodriguez/pry-byebug#112]
I'm hitting this exception when trying to use `pry-byebug` in the context of `nanoc`.

Here is the stack trace.

```
  0. /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/lib/bundler/rubygems_ext.rb:46:in `full_gem_path'
  1. /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/lib/bundler/remote_specification.rb:82:in `method_missing'
  2. /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.4/lib/bundler/rubygems_integration.rb:436:in `block in replace_bin_path'
  3. /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/helpers/path.rb:8:in `bin_file'
  4. /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/helpers/path.rb:12:in `root_path'
  5. /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/helpers/path.rb:38:in `expand_from_root'
  6. /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/helpers/path.rb:16:in `lib_files'
  7. /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/context.rb:25:in `ignored_files'
  8. /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/context.rb:152:in `ignored_file?'
  9. /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/context.rb:126:in `at_return'
```

At that point I'm not sure this is caused by `pry-byebug`, `bundler` or `nanoc`.

That being said, requiring `pry` before calling `binding.pry` instead of requiring `pry-byebug` works for me.

**Comment by gpakosz** [comment]
Thanks @ddfreyne for helping me with this, appreciated.

What's happening is through Nanoc hoops, `Gem::Source::Installed` instance corresponding to `pry-byebug` ends up respond to `#path` which confuses Bundler.
