### ISSUE TITLE
Backtrace not working

### ISSUE THREAD

**Issue by michaeleisel** [deivid-rodriguez/pry-byebug#138]
Hi, when I run `backtrace` in the repl that gets opened up when an exception occurs, I get:
```
ArgumentError: uncaught throw :breakout_nav
from /Library/Ruby/Gems/2.0.0/gems/pry-byebug-3.4.3/lib/pry-byebug/helpers/navigation.rb:13:in `throw'
/Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/pry_instance.rb:529:in `select_prompt': private method `eval' called for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/repl.rb:95:in `read'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/repl.rb:68:in `block in repl'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pry-byebug-3.4.3/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
	from /Library/Ruby/Gems/2.0.0/gems/pry-0.10.4/lib/pry/core_extensions.rb:43:in `pry'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:58:in `block in enter_exception_context'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:204:in `with_program_name'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:56:in `enter_exception_context'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:37:in `rescued'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:17:in `rescue in block (2 levels) in rescue'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:14:in `block (2 levels) in rescue'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:13:in `catch'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:13:in `block in rescue'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:12:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:12:in `rescue'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:73:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/pry-rescue-1.4.5/bin/rescue:52:in `<top (required)>'
	from /usr/local/bin/rescue:23:in `load'
	from /usr/local/bin/rescue:23:in `<main>'
```

**Comment by cyrilchampier** [comment]
if that helps, another trace:
```
[1] pry(#<ZipperTest>)> backtrace
UncaughtThrowError: uncaught throw :breakout_nav
from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/pry-byebug/helpers/navigation.rb:13:in `throw'
/Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/pry_instance.rb:531:in `select_prompt': private method `eval' called for nil:NilClass (NoMethodError)
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/repl.rb:95:in `read'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/repl.rb:68:in `block in repl'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/repl.rb:67:in `loop'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/repl.rb:67:in `repl'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/repl.rb:38:in `block in start'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/input_lock.rb:61:in `__with_ownership'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/input_lock.rb:79:in `with_ownership'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/repl.rb:38:in `start'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/repl.rb:13:in `start'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/pry_class.rb:192:in `start'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-0.11.2/lib/pry/core_extensions.rb:43:in `pry'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:58:in `block in enter_exception_context'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:204:in `with_program_name'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue.rb:56:in `enter_exception_context'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:37:in `rescued'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:17:in `rescue in block (2 levels) in rescue'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:14:in `block (2 levels) in rescue'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:13:in `catch'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:13:in `block in rescue'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:12:in `loop'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/core_ext.rb:12:in `rescue'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/pry-rescue-1.4.5/lib/pry-rescue/minitest.rb:14:in `run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-reporters-1.1.18/lib/minitest/reporters.rb:53:in `run_with_hooks'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:943:in `run_one_method'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:334:in `run_one_method'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:321:in `block (2 levels) in run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:320:in `each'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:320:in `block in run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:360:in `on_signal'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:347:in `with_info_handler'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:319:in `run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/railties-5.1.4/lib/rails/test_unit/line_filtering.rb:9:in `run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `block in __run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `map'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:159:in `__run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:136:in `run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/minitest-5.11.1/lib/minitest.rb:63:in `block in autorun'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/dcyril/.rbenv/versions/2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
``
`

**Comment by deivid-rodriguez** [comment]
This issue is very old, I think this is fixed now. Let me know if it's not!
