### ISSUE TITLE
Loading pry-byebug on Archlinux fails with "cannot load such file -- irb"

### ISSUE THREAD

**Issue by krobelus** [deivid-rodriguez/pry-byebug#335]
Originally reported [here with detailed steps to reproduce](https://gitlab.com/gitlab-org/gitlab-development-kit/-/issues/1127#note_458766094).

In short:

```sh
$ echo > Gemfile << EOF
source "https://rubygems.org"
gem 'pry-byebug', '~> 3.9.0''
EOF
$ bundle install
$ bundle exec ruby -e "require 'pry-byebug'"
/usr/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/commands/irb.rb:4:in `require': cannot load such file -- irb (LoadError)
	from /usr/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/commands/irb.rb:4:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/commands.rb:20:in `require_relative'
	from /usr/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/commands.rb:20:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/core.rb:10:in `require_relative'
	from /usr/lib/ruby/gems/2.7.0/gems/byebug-11.1.3/lib/byebug/core.rb:10:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:3:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/byebug/processors/pry_processor.rb:3:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:3:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug/pry_ext.rb:3:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug/cli.rb:4:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug/cli.rb:4:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/plugins.rb:55:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/plugins.rb:55:in `load_cli_options'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/cli.rb:40:in `each'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/cli.rb:40:in `add_plugin_options'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry/cli.rb:134:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry.rb:78:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-0.13.1/lib/pry.rb:78:in `<top (required)>'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug.rb:3:in `require'
	from /usr/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib/pry-byebug.rb:3:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

This is probably specific to Archlinux. I'm not sure if `irb` should be loaded in this case?

**Comment by deivid-rodriguez** [comment]
Hi!

I actually reported this at https://bugs.archlinux.org/task/62709, and it was fixed by https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/ruby&id=9ce9e857b3de73fd09ff0b5878577c2591351016. Not sure what the release schedule for that change is, since I've never used archlinux.

Anyways, this is a 3rd party issue, and it's already fixed, so closing!
