### ISSUE TITLE
Build failure with ruby-pry-byebug version 3.9.0-1

### ISSUE THREAD

**Issue by vigneshraman** [deivid-rodriguez/pry-byebug#401]
With ruby-pry-byebug version 3.9.0-1, I'm seeing the below build failure,
```
[  179s]   1) Error:
[  179s] Backtrace command#test_0001_shows a backtrace:
[  179s] ArgumentError: invalid byte sequence in US-ASCII
[  179s]     /usr/src/packages/BUILD/test/commands/frames_test.rb:70:in `split'
[  179s]     /usr/src/packages/BUILD/test/commands/frames_test.rb:70:in `block (2 levels) in <class:FramesTest>'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest/test.rb:98:in `block (3 levels) in run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest/test.rb:195:in `capture_exceptions'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest/test.rb:95:in `block (2 levels) in run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:270:in `time_it'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest/test.rb:94:in `block in run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:365:in `on_signal'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest/test.rb:211:in `with_info_handler'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest/test.rb:93:in `run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:1029:in `run_one_method'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:339:in `run_one_method'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:326:in `block (2 levels) in run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:325:in `each'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:325:in `block in run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:365:in `on_signal'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:352:in `with_info_handler'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:324:in `run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `block in __run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `map'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:164:in `__run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:141:in `run'
[  179s]     /usr/lib/ruby/vendor_ruby/minitest.rb:68:in `block in autorun'
[  179s] 
[  179s] 41 runs, 87 assertions, 0 failures, 1 errors, 0 skips
[  179s] Coverage report generated for Unit Tests to /usr/src/packages/BUILD/coverage. 556 / 715 LOC (77.76%) covered.
[  179s] rake aborted!
[  179s] Command failed with status (1): [ruby -w -I"test" /usr/share/rubygems-integration/all/gems/rake-13.0.3/lib/rake/rake_test_loader.rb "test/base_test.rb" "test/breakpoints_test.rb" "test/commands/breakpoints_test.rb" "test/commands/frames_test.rb" "test/commands/stepping_test.rb" "test/processor_test.rb" "test/pry_ext_test.rb" "test/pry_remote_ext_test.rb" "test/thread_lock_test.rb" "test/test_helper.rb" -v]
[  179s] /usr/share/rubygems-integration/all/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
[  179s] Tasks: TOP => default
[  179s] (See full trace by running task with --trace)
[  179s] ERROR: Test "ruby2.7" failed. Exiting.
[  179s] dh_auto_install: error: dh_ruby --install /usr/src/packages/BUILD/debian/ruby-pry-byebug returned exit code 1
[  179s] make: *** [debian/rules:7: binary] Error 25
[  179s] dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```

The same issue is reported in https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/ruby-pry-byebug.html

**Comment by Segaja** [comment]
The same happens with ruby 3.11.0 and ruby-3.4

**Comment by zenspider** [comment]
That's not a build failure. That's a test failing.
